package tech.gulp.lavavisual.ui;

/** Generated by tools/make_logo.py: logo texture widths for pixel scales 1, 1.5 ... 8 (index = 2 x scale - 2). */
final class LogoSizes {
    private LogoSizes() { }
    static final int MENU_H = 30, HUD_H = 16;
    static final int[] MENU_W = {47, 70, 93, 117, 140, 163, 187, 210, 234, 257, 280, 304, 327, 350, 374};
    static final int[] HUD_W = {25, 37, 50, 62, 75, 87, 100, 112, 125, 137, 149, 162, 174, 187, 199};
}
