package tech.gulp.lavavisual.ui;

/** Generated by tools/make_logo.py: logo texture widths for pixel scales 1..8. */
final class LogoSizes {
    private LogoSizes() { }
    static final int MENU_H = 30, HUD_H = 16;
    static final int[] MENU_W = {40, 80, 119, 159, 199, 239, 279, 319};
    static final int[] HUD_W = {21, 42, 64, 85, 106, 127, 149, 170};
}
