plugins {
    id 'com.android.application'
}

android {
    namespace 'tech.gulp.lavavisual.app'
    compileSdk 34

    defaultConfig {
        applicationId 'tech.gulp.lavavisual.app'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName project.version
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources.excludes += 'META-INF/*'
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
