#!/usr/bin/env python3
"""Builds LavaVisual's crisp UI fonts (pip install fonttools).

Minecraft rasterises TTF glyphs at size*oversample pixels and samples them without filtering.
Text is only sharp when one glyph texel covers exactly one screen pixel, so every face is
emitted once per integer scale (1..8) and UiFont picks the face matching guiScale*poseScale.
"""
import json
import math
from pathlib import Path
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.ttGlyphPen import TTGlyphPen

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'tools' / 'fonts'
OUT = ROOT / 'ports' / 'mc26.2' / 'src' / 'main' / 'resources' / 'assets' / 'lavavisual' / 'font'
JAVA = ROOT / 'ports' / 'mc26.2' / 'src' / 'main' / 'java' / 'tech' / 'gulp' / 'lavavisual' / 'ui' / 'Icons.java'

TEXT = set(range(0x20, 0x7F)) | set(range(0xA0, 0x180)) | set(range(0x400, 0x530)) | set(range(0x2000, 0x2070)) \
    | set(range(0x2190, 0x2200)) | {0x20BD, 0x20AC, 0x2116, 0x2122, 0x2212, 0x221E, 0x2248, 0x2260, 0x2264, 0x2265,
                                   0x2713, 0x2715, 0x25CF, 0x25CB, 0x2605, 0x2606, 0x2764, 0x00D7, 0x2715}

ICONS = ['layout-dashboard', 'sparkles', 'hand', 'volume-2', 'palette', 'earth', 'flame', 'x', 'chevron-left',
         'chevron-right', 'save', 'folder-open', 'copy', 'clipboard-paste', 'rotate-ccw', 'power', 'move', 'play',
         'wifi', 'activity', 'gauge', 'clock', 'user', 'server', 'heart', 'shield', 'skull', 'crosshair', 'footprints',
         'sparkle', 'target', 'scan-eye', 'eye', 'wind', 'badge-check', 'cloud-sun', 'zap', 'layers', 'wand-sparkles',
         'map-pin', 'keyboard', 'droplets', 'mouse-pointer-click', 'monitor', 'swords', 'sword', 'music', 'bell',
         'circle-dot', 'orbit', 'star', 'trophy', 'triangle', 'sun', 'moon', 'hand-metal', 'check', 'plus', 'minus',
         'settings', 'sliders-horizontal', 'signal', 'timer', 'mouse', 'ruler', 'heart-pulse', 'crown', 'gem', 'rocket',
         'ghost', 'headphones', 'audio-lines', 'volume-x', 'paintbrush', 'refresh-cw', 'folder', 'info', 'shield-half',
         'medal', 'pencil', 'stamp', 'droplet', 'map', 'map-pinned', 'navigation', 'navigation-2', 'compass', 'flag',
         'trash-2', 'eye-off', 'pipette', 'locate-fixed', 'mountain', 'command', 'rainbow', 'paint-bucket', 'swatch-book',
         'keyboard-off', 'signpost', 'cone', 'rotate-cw', 'move-vertical', 'scaling', 'square-pen', 'search',
         'corner-down-left']

def instance(weight, name):
    font = TTFont(SRC / 'InterVariable.ttf')
    static = instancer.instantiateVariableFont(font, {'wght': weight, 'opsz': 14}, inplace=False)
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ['*']
    options.notdef_outline = True
    options.drop_tables += ['GSUB', 'GPOS', 'GDEF', 'STAT']
    sub = subset.Subsetter(options)
    sub.populate(unicodes=TEXT)
    sub.subset(static)
    static.save(OUT / name)
    print(name, (OUT / name).stat().st_size)

def icons():
    codes = json.loads((SRC / 'lucide-codepoints.json').read_text())
    font = TTFont(SRC / 'lucide.ttf')
    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ['*']
    options.notdef_outline = True
    sub = subset.Subsetter(options)
    sub.populate(unicodes=[codes[n] for n in ICONS])
    sub.subset(font)
    glyf, hmtx, cmap = font['glyf'], font['hmtx'], font.getBestCmap()
    glyph_set = font.getGlyphSet()
    for cp, gname in cmap.items():
        g = glyf[gname]
        if g.numberOfContours == 0:
            continue
        g.recalcBounds(glyf)
        w, h = g.xMax - g.xMin, g.yMax - g.yMin
        s = 900.0 / max(w, h)  # uniform padding inside the 1000-unit em box
        dx = 500 - (g.xMin + w / 2) * s
        dy = 500 - (g.yMin + h / 2) * s
        pen = TTGlyphPen(glyph_set)
        glyph_set[gname].draw(TransformPen(pen, (s, 0, 0, s, dx, dy)))
        fresh = pen.glyph()
        fresh.recalcBounds(glyf)
        glyf[gname] = fresh
        hmtx[gname] = (1000, fresh.xMin)
    font['hhea'].ascent, font['hhea'].descent = 1000, 0
    font.save(OUT / 'icons.ttf')
    print('icons.ttf', (OUT / 'icons.ttf').stat().st_size)
    lines = ['package tech.gulp.lavavisual.ui;', '',
             '/** Lucide icon glyphs (ISC, see licenses/Lucide-ISC.txt), generated by tools/build_fonts.py. */',
             'public final class Icons {', '    private Icons() { }']
    for n in ICONS:
        lines.append('    public static final String %s = "\\u%04X";' % (n.upper().replace('-', '_'), codes[n]))
    lines.append('}')
    JAVA.write_text('\n'.join(lines) + '\n')

def shift(value, n):
    return round(math.ceil(value * n - 1e-9) / n, 4)

def faces():
    for f in OUT.glob('*.json'):
        f.unlink()
    spec = {  # face: (file, size, baseline shift in GUI px)
        'r': ('inter-medium.ttf', 9, 0.5), 'b': ('inter-semibold.ttf', 9, 0.5), 's': ('inter-medium.ttf', 7, 0.0),
        'h': ('inter-semibold.ttf', 12, 2.0), 'i': ('icons.ttf', 10, 3.0), 'j': ('icons.ttf', 8, 2.0),
        'k': ('icons.ttf', 16, 9.0)}
    # Whole and half pixel scales 1, 1.5 ... 8: resized HUD elements use the half steps (face r2_5 = 2.5 px/unit).
    for face, (file, size, dy) in spec.items():
        for half in range(2, 17):
            n = half // 2 if half % 2 == 0 else half / 2
            name = f'{face}{half // 2}' + ('' if half % 2 == 0 else '_5')
            providers = [{'type': 'ttf', 'file': 'lavavisual:' + file, 'shift': [0, shift(dy, n)], 'size': size, 'oversample': n}]
            if face in 'rbsh':
                providers.append({'type': 'reference', 'id': 'minecraft:default'})
            (OUT / f'{name}.json').write_text(json.dumps({'providers': providers}, indent=1) + '\n')
    (OUT / 'ui.json').write_text((OUT / 'r2.json').read_text())

if __name__ == '__main__':
    import sys
    OUT.mkdir(parents=True, exist_ok=True)
    if sys.argv[1:] == ['--faces']:  # only rewrite the face JSONs, keep the font binaries byte-identical
        faces()
        raise SystemExit
    if sys.argv[1:] == ['--icons']:  # only rebuild icons.ttf and Icons.java, keep the Inter binaries byte-identical
        icons()
        raise SystemExit
    instance(500, 'inter-medium.ttf')
    instance(620, 'inter-semibold.ttf')
    icons()
    faces()
