#!/usr/bin/env python3
"""Builds LavaVisual logo assets from a logo drawn on a black background.

    python3 tools/make_logo.py [tools/logo/logo-source.png]

Outputs (mod resources):
  assets/lavavisual/icon.png                     128 x 128 mod icon (Mod Menu / mod list)
  assets/lavavisual/textures/gui/logo/menu_<k>.png  menu header logo, MENU_H units tall at k pixels per unit
  assets/lavavisual/textures/gui/logo/hud_<k>.png   watermark logo, HUD_H units tall
  ui/LogoSizes.java                              texture widths per pixel scale

Minecraft samples GUI textures without filtering, so each size exists once per integer pixel scale (1..8) and is
downsampled here with Lanczos in premultiplied alpha; at draw time one texel covers exactly one screen pixel.
"""
import sys
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "ports/mc26.2/src/main/resources/assets/lavavisual"
JAVA = ROOT / "ports/mc26.2/src/main/java/tech/gulp/lavavisual/ui/LogoSizes.java"
MENU_H, HUD_H, SCALES = 30, 16, range(1, 9)


def extract(path):
    rgb = np.asarray(Image.open(path).convert("RGB"), dtype=np.float64) / 255.0
    lum = rgb.max(axis=2)
    # Background = dark pixels connected to the border; dark details inside the letters stay opaque.
    dark = Image.fromarray(((lum < 0.2) * 255).astype(np.uint8), "L").copy()
    h, w = lum.shape
    for seed in ((0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)):
        if dark.getpixel(seed) == 255:
            ImageDraw.floodfill(dark, seed, 128)
    outside = np.asarray(dark) == 128
    alpha = np.where(outside, np.clip((lum - 0.025) / 0.175, 0, 1), 1.0)
    # Un-multiply the black matte so glows and anti-aliased edges keep their colour on any background.
    color = np.where(outside[..., None], np.clip(rgb / np.maximum(alpha, 1e-3)[..., None], 0, 1), rgb)
    color = np.where(outside[..., None] & (alpha[..., None] < 1), np.minimum(color, np.maximum(rgb, color)), color)
    rgba = np.dstack([color, alpha])
    ys, xs = np.nonzero(alpha > 0.03)
    pad = int(0.02 * max(h, w))
    y0, y1 = max(0, ys.min() - pad), min(h, ys.max() + pad + 1)
    x0, x1 = max(0, xs.min() - pad), min(w, xs.max() + pad + 1)
    return Image.fromarray((rgba[y0:y1, x0:x1] * 255 + 0.5).astype(np.uint8), "RGBA")


def resized(img, width, height):
    return img.convert("RGBa").resize((width, height), Image.LANCZOS).convert("RGBA")


def main():
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tools/logo/logo-source.png"
    logo = extract(source)
    aspect = logo.width / logo.height
    out = RES / "textures/gui/logo"
    out.mkdir(parents=True, exist_ok=True)
    widths = {}
    for name, units in (("menu", MENU_H), ("hud", HUD_H)):
        widths[name] = []
        for k in SCALES:
            th = units * k
            tw = max(1, round(th * aspect))
            resized(logo, tw, th).save(out / f"{name}_{k}.png", optimize=True)
            widths[name].append(tw)
    # Square mod icon: logo centred with a small margin, transparent background.
    size, margin = 128, 6
    fit = size - 2 * margin
    iw, ih = (fit, max(1, round(fit / aspect))) if aspect >= 1 else (max(1, round(fit * aspect)), fit)
    icon = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    icon.alpha_composite(resized(logo, iw, ih), ((size - iw) // 2, (size - ih) // 2))
    icon.save(RES / "icon.png", optimize=True)
    JAVA.write_text(
        "package tech.gulp.lavavisual.ui;\n\n"
        "/** Generated by tools/make_logo.py: logo texture widths for pixel scales 1..8. */\n"
        "final class LogoSizes {\n"
        "    private LogoSizes() { }\n"
        f"    static final int MENU_H = {MENU_H}, HUD_H = {HUD_H};\n"
        f"    static final int[] MENU_W = {{{', '.join(map(str, widths['menu']))}}};\n"
        f"    static final int[] HUD_W = {{{', '.join(map(str, widths['hud']))}}};\n"
        "}\n", encoding="utf-8")
    print(f"logo {logo.width}x{logo.height} aspect {aspect:.3f}; menu {widths['menu']}; hud {widths['hud']}")


if __name__ == "__main__":
    main()
